main:
  push:
    - stages:
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            include: "**/**.md"

$:
  vscode:
    - docker:
        build: .ide/Dockerfile
      runner:
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: start ollama
          script: nohup ollama serve >/dev/null 2>&1 &
        - name: install frontend dependencies
          script: cd frontend && npm install
        - name: install backend dependencies
          script: cd backend && pip install .
        