main:
  push:
    - stages:
        - name: build knowledge base
          image: cnbcool/knowledge-base
          settings:
            include: "**/**.md"

$:
  vscode:
    - docker:
        build: .ide/Dockerfile
      runner:
        tags: cnb:arch:amd64:gpu
      services:
        - vscode
        - docker
      stages:
        - name: start ollama
          script: nohup ollama serve >/dev/null 2>&1 &
        - name: setup dependencies (parallel)
          script: |
            # å¹¶è¡Œå®‰è£…å‰ç«¯å’ŒåŽç«¯ä¾èµ–ä»¥åŠ å¿«é€Ÿåº¦
            (
              if [ -d /tmp/frontend/node_modules ]; then
                echo "ðŸ“¦ Linking frontend dependencies..."
                cd frontend && ln -sf /tmp/frontend/node_modules node_modules 2>/dev/null || npm install --prefer-offline --no-audit
              else
                echo "ðŸ“¦ Installing frontend dependencies..."
                cd frontend && npm install --prefer-offline --no-audit
              fi
            ) &
            (
              echo "ðŸ Installing backend dependencies..."
              cd backend && pip install . --no-deps 2>/dev/null || pip install .
            ) &
            wait
            echo "âœ… Dependencies ready!"
        